development: &defaults
    client_id: 294574140563371
    client_secret: 92b860b087093b91f6629afbd047d1e1
    scope: user_photos,user_location,user_events,user_location,email,user_checkins,create_event,rsvp_event,offline_access,publish_checkins,publish_stream
    canvas_url: http://apps.facebook.com/hangplan

test:
  <<: *defaults

production:
  <<: *defaults