development: &defaults
    client_id: 294574140563371
    client_secret: 92b860b087093b91f6629afbd047d1e1
    scope: user_events, user_location,email,read_friendlists,user_checkins,create_event,rsvp_event,manage_notifications
    canvas_url: http://apps.facebook.com/fb-graph-sample-dev

test:
  <<: *defaults

production:
  <<: *defaults